### ISSUE TITLE
Request for example 

### ISSUE THREAD

**Issue by ioannaMitropoulou** [ChrisPappalardo/eparse#10]
Hello, 
Could you provide an example of how to parse and query an Excel sheet from Python using eparse? I couldn't find a clear example in the README file.
Thank you!

**Comment by ChrisPappalardo** [comment]
Parse excel file(s) to a SQLite database (https://github.com/ChrisPappalardo/eparse?tab=readme-ov-file#sqlite3):
`$ eparse -f <path_to_files> -o sqlite3:///path/filename.db parse -z`

Each cell of extracted table data is added to the database with the following fields (https://github.com/ChrisPappalardo/eparse?tab=readme-ov-file#stdout):

    row - 0-indexed table row number
    column - 0-indexed table column number
    value - the value of the cell as a str
    type - the implied python type of the data found
    c_header - the column header
    r_header - the row header
    excel_RC - the RC reference from the spreadsheet (e.g. B10)
    sheet - the name of the sheet
    f_name - the name of the file

Query data in the SQLite database using eparse (https://github.com/ChrisPappalardo/eparse?tab=readme-ov-file#query):
`$ eparse -i sqlite3:///.files/<db_file> -o stdout:/// query --filter f_name "somefile.xlsx"`

Or use a SQLite client and run raw SQL queries:
`$ sudo apt-get install -y sqlite3-tools`
`$ sqlite3 .files/<db_file>`
`sqlite> SELECT * FROM excelparse LIMIT 1;`

**Comment by ioannaMitropoulou** [comment]
Hello, 
I apologize for not making my request a bit clearer. I would like to use this code from inside a python script, and not from the command line. Would you be able to guide me through the process of doing that?
Thank you so much for your help!

**Comment by ChrisPappalardo** [comment]
Sure, I'll figure out a simple example and either update the README or post it here.

**Comment by ChrisPappalardo** [comment]
Hi @ioannaMitropoulou , the README has been updated to include a [second python example](https://github.com/ChrisPappalardo/eparse/blob/1fed2cf6876545a163066d07f42b97e259b67315/README.rst?plain=1#L120) to show how to loop through files in a directory and extract cells related to a targeted column name.  If you need further guidance, you should look at the [command-line interface](https://github.com/ChrisPappalardo/eparse/blob/main/eparse/cli.py) to see how the CLI commands were implemented in python.
