### ISSUE TITLE
NA cells tolerance

### ISSUE THREAD

**Issue by Antonio-Velasco** [ChrisPappalardo/eparse#3]
When parsing tables NA cells may split the content in more than one table.
These NA cells may belong to a merrged cell or to an empty row beneath the headers. Resulting in the headers parsed as one table and the content as a different one.
When feeding tables to LLMs this is not ideal.

I propose the addition of two variables that allow to add some tolerance for NA cells which in some cases may help the user extracting tables as a whole:

https://github.com/ChrisPappalardo/eparse/pull/2

**Comment by ChrisPappalardo** [comment]
Hi @Antonio-Velasco, thanks for opening this issue and your PR.  This seems like a good enhancement.  I don't think you intended for empty columns and rows to always be added to the parsed table, however, and with the algorithm you proposed in the PR, this will always be the case.  I think we need a third parameter to strip NAs from the table when an entire row and/or column at the edges is NA.  We also need unit tests for this feature to accept the PR.  I will push a commit to your fork with these changes.

**Comment by ChrisPappalardo** [comment]
Merged into main.
